export const BASE_URL       = 'http://localhost:8000'
export const BASE_URL_LOBBY = 'ws://localhost:8000/ws/'

// ENDPOINT APP

export const API_ENDPOINT_LIST_ROBOTS         = '/robot/list'
export const API_ENDPOINT_CREATE_GAME         = '/match/new'
export const API_ENDPOINT_LOGIN               = '/login'
export const API_ENDPOINT_LIST_GAMES          = '/match/list'
export const API_ENDPOINT_REGISTER            = '/user/register/'
export const API_ENDPOINT_SIMULATION          = '/simulation'
export const API_ENDPOINT_UPLOAD_BOT          = '/robot/new/'
export const API_ENDPOINT_WINNER              = '/match/results/'
export const API_ENDPOINT_LEAVE_GAME          = '/match/exit'
export const API_ENDPOINT_START_GAME          = '/match/start'
export const API_ENDPOINT_JOIN_GAME           = '/match/join'
export const API_ENDPOINT_VERIFY              = '/verify/'
export const API_ENDPOINT_SEND_RECOVER_EMAIL  = '/send_email_password_recover'
export const API_ENDPOINT_PASSWORD_RECOVER    = '/password_recover'
export const API_ENDPOINT_EDIT_ROBOT          = '/robot/edit_implementation'
export const API_ENDPOINT_DOWNLOAD_ROBOT_CODE = '/robot/code/'
export const API_ENDPOINT_CHANGE_PASSWORD     = '/user/edit/password'
export const API_ENDPOINT_USER_DATA           = '/user/profile'
export const API_ENDPOINT_CHANGE_AVATAR       = '/user/profile/change_avatar'